FROM gradle:9.6-jdk25 AS builder

WORKDIR /app


COPY gradlew .
COPY gradle ./gradle
COPY build.gradle .
COPY settings.gradle .


RUN ./gradlew --no-daemon dependencies || true


COPY . .


EXPOSE 8000

CMD ["./gradlew", "bootRun"]
