spring.application.name=media

spring.main.allow-bean-definition-overriding=true

# MVC settings
spring.mvc.throw-exception-if-no-handler-found=true

# Web resources
spring.web.resources.add-mappings=false

# MongoDB connection
spring.data.mongodb.uri=mongodb://amine:1234@localhost:27017/DB?authSource=admin

# tomcat settings
server.port=8888

# dev tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# kafka
# spring.kafka.bootstrap-servers=kafka:9092
# spring.kafka.consumer.group-id=products-group
# spring.kafka.consumer.auto-offset-reset=earliest
# spring.kafka.consumer.properties.spring.json.trusted.packages=*

# eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Devtools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# Spring Content
spring.content.fs.filesystem-root=/storage