spring.application.name=media

spring.main.allow-bean-definition-overriding=true

# MVC settings
spring.mvc.throw-exception-if-no-handler-found=true

# Web resources
spring.web.resources.add-mappings=false

# MongoDB connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/media}

# tomcat settings
server.port=8888

# dev tools
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false


# kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=media-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.*
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# eureka
eureka.client.service-url.defaultZone=${DISCOVERY}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=media-service
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=${server.port}


# Spring Content
spring.content.fs.filesystem-root=/storage
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
server.ssl.enabled=true
server.ssl.key-store-password=${KEY_STORE_PWD}
server.ssl.key-store-type=${KEY_STORE_TYPE}

# For mTLS — require client cert from gateway
server.ssl.client-auth=need
server.ssl.key-store=${CERTIFICATE_PATH}
server.ssl.trust-store=${TRUSTSTORE_PATH}
server.ssl.trust-store-password=${TRUST_STORE_PWD}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=media-service
media.cleanup.temporary-retention-minutes=${TEMPORARY_MEDIA_RETENTION_MINUTES:60}
media.cleanup.interval-ms=${MEDIA_CLEANUP_INTERVAL_MS:900000}
