services:
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    container_name: eureka-server
    mem_limit: 384m
    restart: unless-stopped
    networks:
      - shared-net
    volumes:
      - eureka-server-certs:/app/resources/certs:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared-net:
    external: true

volumes:
  eureka-server-certs:
    external: true
