services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: buy01-frontend
    mem_limit: 128m
    environment:
      API_BASE_URL: ${FRONTEND_API_BASE_URL:-}
    networks:
      - shared-net
    ports:
      # - 4200:443
      - "80:80"
      - "443:443"
    volumes:
      - frontend_caddy_data:/data
      - frontend_caddy_config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--no-check-certificate", "--tries=1", "--spider", "https://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  shared-net:
    external: true
volumes:
  frontend_caddy_data:
  frontend_caddy_config:
