services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    mem_limit: 512m
    restart: unless-stopped
    env_file:
      - .env.gateway
    volumes:
      - gateway-certs:/app/resources/certs:ro
    networks:
      - shared-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  gateway-certs:
    external: true

networks:
  shared-net:
    external: true
