services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "10000:10000"
    environment:
      DISCOVERY : http://eureka-server:8761/eureka
      REDIS-HOST : redis
      REDIS-PORT : 6379
      JAVA_TOOL_OPTIONS : -Djavax.net.ssl.trustStore=/app/resources/certs/truststore.p12 -Djavax.net.ssl.trustStorePassword=123123 -Djavax.net.ssl.keyStore=/app/resources/certs/gateway.p12 -Djavax.net.ssl.keyStorePassword=123123
    volumes:
      - backend_m2:/root/.m2
      - ~/.m2:/root/.m2
      - ./certs/gateway.p12:/app/resources/certs/gateway.p12:ro
      - ./certs/truststore.p12:/app/resources/certs/truststore.p12:ro
    networks:
      - shared-net

volumes:
  mongo_data:
  backend_m2:

networks:
  shared-net:
    external: true
