
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123123
    ports:
      - "27017:27017"
    volumes: 
      - mongo_data:/data/db
    networks:
      - app-network

  users-service:
    build: 
      context: ./service
    restart: on-failure
    container_name: users-service
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: 4cfeee175e498e32039c7e804957663cb8e09b58a0902bf56222acab991cb4bd955bdf3c25942131e432c59be57d411c31f25c6432bd18fd8f006b8913636da2
      JWT_EXP: 3600000
      MONGODB_USERNAME: admin
      MONGODB_PWD: 123123
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGO_DB: users_db
      MONGODB_AUTH: admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./service/src:/app/src
      - ~/.gradle:/root/.gradle
    working_dir: /app

volumes:
  mongo_data:

networks:
  app-network:
    external: true
