spring.application.name=config-server

# server
server.port=9999


# eureka
eureka.client.service-url.defaultZone=${DISCOVERY:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# config
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:/home/amine/Desktop/buy-01/configs