services:
  config-server:
    build:
      context: ./config
    container_name: config-server
    ports:
      - "9999:9999"
    environment:
      DISCOVERY : http://eureka-server:8761/eureka
    networks:
      - shared-net

networks:
  shared-net:
    external: true
