spring.application.name=eureka-server


# Server port
server.port=8761

# Eureka server settings

# Eureka Server itself does not need to register with another Eureka Server
eureka.client.register-with-eureka=false

# Eureka Server does not need to fetch registry information from other servers
eureka.client.fetch-registry=false 

# expose all actuator endpoints for monitoring
management.endpoints.web.exposure.include=*

# show health details always
management.endpoint.health.show-details=always