spring.application.name=gateway

server.port=10000

jwt.public-key=${JWT_PUBLIC_KEY_PATH:file:/app/resources/certs/jwt-public.pem}
eureka.client.registry-fetch-interval-seconds=60

eureka.instance.lease-renewal-interval-in-seconds=60
eureka.instance.lease-expiration-duration-in-seconds=120

eureka.client.service-url.defaultZone=${DISCOVERY}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# redis
spring.redis.host=${REDIS-HOST}
spring.redis.port=${REDIS-PORT}
logging.level.org.springframework.data.redis=INFO
logging.level.org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter=INFO

# 1. Critical for handling OPTIONS requests before they hit your routes
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# 2. Define which paths this applies to (use [/**] for all)
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200/,https://localhost:4200/,https://marketplace.bouchikhi.com
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600

server.ssl.enabled=true
server.ssl.key-store-password=${KEY_STORE_PWD}
server.ssl.key-store-type=${KEY_STORE_TYPE}

# For mTLS — require client cert from gateway
server.ssl.client-auth=none
server.ssl.key-store=${CERTIFICATE_PATH:file:/app/resources/certs/gateway.p12}
server.ssl.trust-store=${TRUSTSTORE_PATH:file:/app/resources/certs/truststore.p12}
server.ssl.trust-store-password=${TRUST_STORE_PWD}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=users-service
