services:
  media-service-mongodb:
    build: ./database
    container_name: media-service-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: amine
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: DB
    volumes:
      - mongo_data:/data/db
    networks:
      - shared-net

  media-service:
    build:
      context: ../
      dockerfile: ./media-service/media/Dockerfile
    container_name: media-service
    ports:
      - "8888:8888"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://amine:1234@media-service-mongodb:27017/DB?authSource=admin
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DISCOVERY : http://eureka-server:8761/eureka
    depends_on:
      - media-service-mongodb
    volumes:
      - media_m2:/root/.m2
    networks:
      - shared-net

volumes:
  mongo_data:
  media_m2:

networks:
  shared-net:
    external: true
