FROM gradle:9.3.1-jdk25-noble
WORKDIR /app

COPY build.gradle settings.gradle ./
RUN gradle dependencies

COPY src ./src

EXPOSE 8080
CMD ["bash", "-c", "gradle bootRun & gradle classes --continuous"]
