
server.port=10000

jwt.public-key=classpath:keys/public.pem
eureka.client.registry-fetch-interval-seconds=60

eureka.instance.lease-renewal-interval-in-seconds=60
eureka.instance.lease-expiration-duration-in-seconds=120

eureka.client.service-url.defaultZone=${DISCOVERY}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# redis
spring.redis.host=${REDIS-HOST}
spring.redis.port=${REDIS-PORT}
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.cloud.gateway.filter.ratelimit.RedisRateLimiter=DEBUG

# 1. Critical for handling OPTIONS requests before they hit your routes
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

# 2. Define which paths this applies to (use [/**] for all)
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true
spring.cloud.gateway.globalcors.corsConfigurations.[/**].maxAge=3600
