# Application name
spring.application.name=products

# MVC settings
spring.mvc.throw-exception-if-no-handler-found=true

# Web resources
spring.web.resources.add-mappings=false

# MongoDB connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# tomcat settings
server.port=8000

# dev tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=products-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


# eureka
eureka.client.service-url.defaultZone=eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true