# Application name
spring.application.name=products

# MVC settings
spring.mvc.throw-exception-if-no-handler-found=true

# Web resources
spring.web.resources.add-mappings=false

# MongoDB connection
spring.data.mongodb.uri=mongodb://amine:1234@mongodb:27017/DB?authSource=admin&uuidRepresentation=standard

# JWT settings
jwt.secret=n9B7Fh8X3Cwq2mRzVYp0Q6L8sA1T5EJZkW4dUoM+KxHcR7eIPlmG2NfaSb0y
jwt.expiration=86400000

# tomcat settings
server.tomcat.port=8000