# Application name
spring.application.name=products

# MVC settings
spring.mvc.throw-exception-if-no-handler-found=true

# Web resources
spring.web.resources.add-mappings=false

# MongoDB connection
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT settings
jwt.secret=n9B7Fh8X3Cwq2mRzVYp0Q6L8sA1T5EJZkW4dUoM+KxHcR7eIPlmG2NfaSb0y
jwt.expiration=86400000

# tomcat settings
server.port=8000

# dev tools
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true


# kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=products-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true