services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379" 
    networks:
      - shared-net
    restart: unless-stopped

networks:
  shared-net:
    external: true